language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-nodejs-module' ]; then cd .. && eval "mv $currentfolder generator-nodejs-module" && cd generator-nodejs-module; fi
